rooms = {
    'entry': {
        'description': 'To be added...',
        'north': 'great hall',
        'south': 'library',
        'west': 'great staircase',
        'look': {
            'north': 'Looking North. To be added...',
            'east': 'Looking East. To be added...',
            'south': 'Looking South. To be added...',
            'west': 'Looking West. To be added...',
        },
    },
    'great hall': {
        'description': 'To be added...',
        'northeast': 'kitchen',
        'north': 'pantry',
        'northwest': 'buttery',
        'south': 'entry',
        'west': 'garden',
        'look': {
            'north': 'To be added...',
            'east': 'To be added...',
            'south': 'To be added...',
            'west': 'To be added...',
        },
        'item': 'sword',
    },
    'kitchen': {
        'description': 'To be added...',
        'north': 'larder',
        'east': 'servant\'s quarters',
        'south': 'great hall',
        'west': 'pantry',
        'look': {
            'north': 'To be added...',
            'east': 'To be added...',
            'south': 'To be added...',
            'west': 'To be added...',
        },
    },
    'pantry': {
        'description': 'To be added...',
        'east': 'kitchen',
        'south': 'great hall',
        'west': 'buttery',
        'look': {
            'north': 'To be added...',
            'east': 'To be added...',
            'south': 'To be added...',
            'west': 'To be added...',
        },
        'item': 'potion',
    },
    'buttery': {
        'description': 'To be added...',
        'south': 'great hall',
        'west': 'kitchen',
        'look': {
            'north': 'To be added...',
            'east': 'To be added...',
            'south': 'To be added...',
            'west': 'To be added...',
        },
        'character': 'butler',
    },
    'larder': {
        'description': 'To be added...',
        'south': 'kitchen',
        'look': {
            'north': 'To be added...',
            'east': 'To be added...',
            'south': 'To be added...',
            'west': 'To be added...',
        },
    },
    'servant\'s quarters': {
        'description': 'To be added...',
        'west': 'kitchen',
        'look': {
            'north': 'To be added...',
            'east': 'To be added...',
            'south': 'To be added...',
            'west': 'To be added...',
        },
        'character': 'ogre',
    },
    'garden': {
        'description': 'To be added...',
        'east': 'great hall',
        'look': {
            'north': 'To be added...',
            'east': 'To be added...',
            'south': 'To be added...',
            'west': 'To be added...',
        },
        'item': 'key',
    },
    'library': {
        'description': 'To be added...',
        'north': 'entry',
        'look': {
            'north': 'To be added...',
            'east': 'To be added...',
            'south': 'To be added...',
            'west': 'To be added...',
        },
        'item': 'dagger',
    },
    'great staircase': {
        'description': 'To be added...',
        'up': 'solar',
        'down': 'entry',
    },
    'solar': {
        'description': 'To be added...',
        'west': 'great staircase',
        'look': {
            'north': 'To be added...',
            'east': 'To be added...',
            'south': 'To be added...',
            'west': 'To be added...',
        },
        'character': 'princess',
    },
}