rooms = {
    'entry': {
        'description': 'The entry is not a room, but more of a hallway. In front of you you see the great staircase.\nTo the left the entrance to the library. And to your right the entrance to the great hall.',
        'north': 'great hall',
        'south': 'library',
        'west': 'great staircase',
        'look': {
            'north': 'Looking North. To be added...',
            'east': 'Looking East. To be added...',
            'south': 'Looking South. To be added...',
            'west': 'Looking West. To be added...',
        },
    },
    'great hall': {
        'description': 'The great hall is the center of the castle and the main entertaining area.\nAs you enter you see the entrances on the far wall to the the buttery, pantry and kitchens. On the left you see a door leading to the garden.',
        'northeast': 'kitchen',
        'north': 'pantry',
        'northwest': 'buttery',
        'south': 'entry',
        'west': 'garden',
        'look': {
            'north': 'To be added...',
            'east': 'To be added...',
            'south': 'To be added...',
            'west': 'To be added...',
        },
        'item': 'sword',
    },
    'kitchen': {
        'description': 'To be added...',
        'north': 'larder',
        'east': 'servant\'s quarters',
        'south': 'great hall',
        'west': 'pantry',
        'look': {
            'north': 'To be added...',
            'east': 'To be added...',
            'south': 'To be added...',
            'west': 'To be added...',
        },
    },
    'pantry': {
        'description': 'The pantry is a room where food, provisions or dishes are stored and served in an ancillary capacity to the kitchen.\nThere were separate rooms for the various service functions and food storage. A pantry was where bread was kept and food preparation associated with it done.\nThe head of the office responsible for this room was referred to as a pantler.',
        'east': 'kitchen',
        'south': 'great hall',
        'west': 'buttery',
        'look': {
            'north': 'To be added...',
            'east': 'To be added...',
            'south': 'To be added...',
            'west': 'To be added...',
        },
        'item': 'potion',
    },
    'buttery': {
        'description': 'The buttery was a domestic room in a castle or large medieval house. It was one of the offices pertaining to the kitchen.\nIt was generally a room close to the Great Hall and was traditionally the place from which the yeoman of the buttery served beer and candles to those lower members of the household not entitled to drink wine.',
        'south': 'great hall',
        'west': 'kitchen',
        'look': {
            'north': 'To be added...',
            'east': 'To be added...',
            'south': 'To be added...',
            'west': 'To be added...',
        },
        'character': 'butler',
    },
    'larder': {
        'description': 'The larder is a cool area for storing food prior to use. Larders were commonplace in houses before the widespread use of the refrigerator.\nEssential qualities of a larder are that it should be:as cool as possible, close to food preparation areas, constructed so as to exclude flies and vermin, easy to keep clean, and equipped with shelves and cupboards appropriate to the food being stored.',
        'south': 'kitchen',
        'look': {
            'north': 'To be added...',
            'east': 'To be added...',
            'south': 'To be added...',
            'west': 'To be added...',
        },
    },
    'servant\'s quarters': {
        'description': 'This area of the house is reserved for the servants to sleep.',
        'west': 'kitchen',
        'look': {
            'north': 'To be added...',
            'east': 'To be added...',
            'south': 'To be added...',
            'west': 'To be added...',
        },
        'character': 'ogre',
    },
    'garden': {
        'description': 'To be added...',
        'east': 'great hall',
        'look': {
            'north': 'To be added...',
            'east': 'To be added...',
            'south': 'To be added...',
            'west': 'To be added...',
        },
        'item': 'key',
    },
    'library': {
        'description': 'To be added...',
        'north': 'entry',
        'look': {
            'north': 'To be added...',
            'east': 'To be added...',
            'south': 'To be added...',
            'west': 'To be added...',
        },
        'item': 'dagger',
        'needs': 'key',
    },
    'great staircase': {
        'description': 'To be added...',
        'up': 'solar',
        'down': 'entry',
    },
    'solar': {
        'description': 'The room in the castle called the Solar was intended for sleeping and private quarters and used by the Lord\'s family.\nIt became a private sitting room favoured by the family. The solar suite of rooms was extended to include a wardrobe.',
        'west': 'great staircase',
        'look': {
            'north': 'To be added...',
            'east': 'To be added...',
            'south': 'To be added...',
            'west': 'To be added...',
        },
        'character': 'princess',
    },
}